---
title: "Unfinished Stories"
author: "DK"
date: "2025-03-05"
draft: yes
categories: [build]
---

信言不美，美言不信；善者不辯，辯者不善

People that speak or write are not the true way.

The true founders were too busy living their teachings.

My parents did not say much, too busy surviving.

Up to us to remember and fulfill

Looking at photos of grandchildren is a moment of gratitude and wonder.

During the time of own child rearing, one seldom appreciates what gift children are.

When the grandchildren are born, through trials, one's appreciation for life has expanded.

It is a marvel how grandchildren take after their parents yet there is a trace of you in them

To fulfill the mission of parents in their own unique way.

Remember sayings of my parents more than formulas and principles studied at school.

Nowadays, a plethora of tools to remind and recall various factions and enclaves that were once only reserved for well endowed individuals.

One can argue the need for a structured studying and awarding of diplomas of accomplishment.

Great ones do not write their messages, for they are busy making their world better

Realizing their vision.

Then it is up to us to complete their messages
