---
title: "Customer King"
author: "DK"
date: "2025-06-13"
draft: yes
categories: [aging]
---

Working with Japanese, was hoping to learn some secrets.

Specifics of the manufacturing prowess that made their products a desirable item

I was in Shizuoka Prefecture.

Specifically Hamamatsu and Fukuroi to learn about the in-line, dual material extrusion.

The extruded product would be used as a micro catheter (less than 1mm OD) for delivering embolization and cancer drugs.

After days of going over the basics, we were ready for some deep dive into how they make their products.

How they keep it consistent.

Training and focus on the target.

We were there for a 6-week training.

They were planning on a 1.5 year training for the technician.

They offered no magic formula or insight.

Just work on meeting the target.

Their focus was understanding and meeting the specifications.

No tolerance, just relentless pursuit of meeting the target.

In Japanese business culture, the concept "customer is god" (お客様は神様, okyakusama wa kamisama) **emphasizes the high regard and respect given to customers**. This idea goes beyond mere politeness and reflects a deep-seated cultural value where businesses strive to anticipate and fulfill customer needs with exceptional service. It's an ideal that shapes interactions and experiences in various settings, from retail to hospitality. 
