---
title: "Man from 長春"
author: "DK"
date: "2025-05-18"
draft: yes
categories: [gathering]
---

There was a time, when one had to drive for a long distance, to eat Korean Food.

Over 1000 km, to Los Angeles area.

Without flight options and lacking choices common in big cities, one would wait until business trips or schedule a family vacations around Southern California Korean neighborhoods.

Now days, one can fly out of KPVU and visit a coastal city and return home within the same day.

And many of the well known restaurant and bakery chains can be reached within an hour of driving.

------------------------------------------------------------------------

Couple times a month, we go to the big city to the north. For business related shopping.

We have a set route or routine. Shop at a few wholesale places followed by a lunch.

Typically we choose a Korean restaurant, staffed by a Hispanic workers. Sometimes restaurant choices are made, not so much for food but for sentimentl reasons.

We waved to the cooks that would prepare the meal, behind the glass wall. As we often do, we ran into an acquaintance. Met her son, daughter-in-law and her mother.

The regular, nostalgic dishes were ordered.

Afterwards, drove across town to be at the new gathering place for Asians and those familiar with Asian cuisine.

No shortage of options, plus new building were being built.

Stopped by a stall that was selling 雞爪

I hadn't seen a wholesale offering of them in decades.

Started a conversation with the owner.

I asked a few questions in my very limited 普通话.

Asked about the dishes and where he was from

Surprisingly he understood me.

(Thinking it over, I think he anticipated my questions rather than actually hearing my pronunciations).

I was happy that he carried on the conversation and told him of the areas I have visited.

And the variety of offering of that boundless continent or a union of multi-national, cultural states or provinces.

It brought back memories of feeling the energy of its citizens and eager businessmen ready to make deals.

------------------------------------------------------------------------

For dinner, visited a place in South Provo, run by a Vietnamese family.

The place was recommended by a Vietnamese co-worker.

As we were getting ready for a feast, met a member from the YSA days

It was good to catch up.

------------------------------------------------------------------------

Grateful that we have a full array of options.

But as we settled down to eat, after the church, was reminded how a simple dish from childhood is the best.

Sister K made a simple, 맑은 감자국 (clear soup made with potatoes) Golden potatoes, cut like a fat french fries, just a touch of spices.

Yes there are many options in life, As Led Zeppelin said a while back,

> Yes, there are two paths you can go by, but in the long run There's still time to change the road you're on

Today, we saved the driving for later and stay home and enjoyed a simple meal.
