---
title: "Interpreters and Translators"
author: "DK"
date: "2025-03-04"
draft: yes
categories: [learning]
---

For 7 years, I worked with a team from Fukuroi, Shizuoka. (静岡県, 袋井市)

Our goal was to move a manufacturing line and furthermore, develop personnel that could build the product using that equipment.

Industrial move or transfer, like a domestic move is challenging.

In addition, this transfer involved not only great distance and time zone but also language barrier.

Most workers didn't speak any English. None of the contingent from US spoke any 日本語 All of the documents were in 平仮名, カタカ, Romaji and 漢字

If that wasn't enough, our company representative reproached me for sending a non-drinking, foreigner to work on the project.

Made our way through, due to the extraordinary patience and accomodation by the Japanese team. We just had to show up and learn, practice and remember.

And make it our own,

------------------------------------------------------------------------

The translation of procedure proved to be a major challenge Initially we used the Google Translate and Microsoft Word's translate full document option. Machine assisted translation was in its infancy and there were many inconsistencies.

We aked a translation firm to convert rest of the dozen or so documents. We had the translation but we needed interpretation of its meaning. Only one who could explain the meaning didn't speak our language.

We were stuck.

Only solution was to send our associates, who would work with their associates. Be trained on the work to be done.

Everyone involved was in agreement. Only difference to be resolved was length of the training period. We were off by factor of nearly 20.

Japanese team suggested multiple years. Our team thought few weeks was sufficient.

We settled at 6 weeks of training.

Which side was more accurate, the time will confirm.

------------------------------------------------------------------------

In the intervening years.

Gradual translation has transformed to instant, AI assisted conversion. Also there is no shortage of interpretation of results.

Where are ones suggested length of time necessary to make it our own. Always relying others to make meaning for us.
