---
title: "Parade and Progression"
author: "DK"
date: "2025-07-04"
draft: yes
categories: [celebrations]
---

Each summer towns in Utah County hold a public celebration.

When children were in marching bands, we would make plans to be present

## Public Parade

Public are invited, and some choose to spend the night in order to stake a spot.

My children participated once.

What would we add or take away

## Private Progression

Less interesting but far more important is the private efforts and celebrations

We are all marching to a same location.

Some had a start and all marching at different rate

Went to a parade, for the first time in a long while. It seems we went every year.

We didn't camp but one year we had friends that did and saved space for us. Along University Avenue and 2nd North, on the east side. East side because that side is shaded longer than the other side.

We had Sister K's sister's family. Sister K's mom and dad And Sister K's Grandmother Song

Today, I showed up after the parade started. Went down towards the end of the parade route, so that I didn't miss any.

I was alone.

The crowd was gathered, mostly in groups of families They brought chairs, awnings, tents, and whatever made them more comfortable It was all facing the parade route, the Center Street.

Did I grow up or had parade changed

Not going to campout for 1.5 hours of enjoyment For I could get enjoyment by walking around and occasionally checking in to the scene

Whereas I tried to get as much of the scene as possible. I focused on individual efforts.

No children marched with bands But I saw fellow citizens and neighbors, driving, shooting water guns and passed by as elected officials.

Like most times, I was alone but I felt at one with the happenings. Unlike (чен) Matsuris I attended in Japan, I knew and understand the language and the purpose of the event.

There were more people I knew that were in the parade than ones watching it.

## Public and Private Celebrations
